### ISSUE TITLE
Document project setup for new grammars

### ISSUE THREAD

**Issue by savq** [lezer-parser/website#16]
I'm interested in contributing to an existing lezer grammar, and also creating a new lezer grammar from scratch. However, the existing docs don't explain how to install and get started with lezer. The [basic example](https://lezer.codemirror.net/examples/basic/) explains the syntax for lezer grammars but assumes you've already installed `lezer-generator` (and links to the API reference, which again doesn't explain this).

I've seen some lezer grammars use `yarn` or `rollup`, but it's not clear whether these are necessary or just a preference of the developers. I know this might be obvious to a web developer, but I'm not a web developer.

For comparison, the tree-sitter docs for [creating parsers](https://tree-sitter.github.io/tree-sitter/creating-parsers) start with a list of dependencies, installation steps, project setup and a sanity check to ensure the development environment has been set up correctly. I'd be great if lezer had a similar section in its documentation.

**Comment by marijnh** [comment]
I've added [an example](https://lezer.codemirror.net/examples/setup/) that goes through this in a bit more detail.
